export interface DishInfo {
  price: number;
  englishName: string;
  name: string;
  id: string;
  image: string;
  type: string;
}

export const UNKNOWN_DISH_INFO = {
  price: 0,
  englishName: "Unknown",
  name: "Unknown",
  id: "Unknown",
  image: "Unknown",
  type: "Unknown",
};

const DISHES: Array<DishInfo> = [
  {
    price: 73000,
    englishName: "Free-range chicken sauteed with lemongrass and chilli",
    name: "Gà xào sả ớt",
    type: "chicken",
    image: "G001",
    id: "G001",
  },
  {
    price: 73000,
    englishName: "Free-range chicken braised with coconut milk",
    name: "Gà khìa nước cốt dừa",
    type: "chicken",
    image: "G002",
    id: "G002",
  },
  {
    price: 73000,
    englishName: "Free-range chicken sauteed in green pepper sauce",
    name: "Gà sốt muối ớt xanh",
    type: "chicken",
    image: "G003",
    id: "G003",
  },
  {
    price: 80000,
    englishName: "Deep fried chicken wings with fish sauce",
    name: "Cánh gà chiên nước mắm",
    type: "chicken",
    image: "G004",
    id: "G004",
  },
  {
    price: 73000,
    englishName: "Free-range chicken braised with ginger",
    name: "Gà kho gừng",
    type: "chicken",
    image: "G006",
    id: "G006",
  },
  {
    price: 52000,
    englishName: "Fried egg with minced pork and onion",
    name: "Trứng chiên thịt",
    type: "egg",
    image: "G007",
    id: "G007",
  },
  {
    price: 66000,
    englishName: "Fried egg with mushroom",
    name: "Trứng xào nấm",
    type: "egg",
    image: "G008",
    id: "G008",
  },
  {
    price: 45000,
    englishName: "Fried egg with tomato",
    name: "Trứng chiên cà chua",
    type: "egg",
    image: "G009",
    id: "G009",
  },
  {
    price: 88000,
    englishName: "Roasted duck sauteed with pickled cabbage",
    name: "Vịt quay xào dưa cải",
    type: "duck",
    image: "G010",
    id: "G010",
  },
  {
    price: 83000,
    englishName: "Sauteed duck with salt",
    name: "Vịt rang muối",
    type: "duck",
    image: "G011",
    id: "G011",
  },
  {
    price: 83000,
    englishName: "Sauteed duck with galangal",
    name: "Vịt rang riềng",
    type: "duck",
    image: "G012",
    id: "G012",
  },
  {
    price: 80000,
    englishName: "Boiled duck dip in fish sauce with ginger",
    name: "Vịt luộc chấm mắm gừng",
    type: "duck",
    image: "G013",
    id: "G013",
  },
  {
    price: 83000,
    englishName: "Sauteed duck with spicy sauce",
    name: "Vịt xào cay",
    type: "duck",
    image: "G015",
    id: "G015",
  },
  {
    price: 73000,
    englishName: "Steam minced pork in sauce of macerated fish",
    name: "Mắm chưng",
    type: "pork",
    image: "G016",
    id: "G016",
  },
  {
    price: 65000,
    englishName: "Vegetable braised in fermented tofu",
    name: "Rau củ kho chao",
    type: "vegetables",
    image: "G018",
    id: "G018",
  },
  {
    price: 76000,
    englishName: "Pork belly cooked with palm sugar caramel",
    name: "Ba rọi kho đường thốt nốt",
    type: "pork",
    image: "G019",
    id: "G019",
  },
  {
    price: 76000,
    englishName: "Pork belly stir fried with shrimp paste",
    name: "Ba rọi xào ruốc sả",
    type: "pork",
    image: "G021",
    id: "G021",
  },
  {
    price: 85000,
    englishName: "Roasted pork sauteed with garlic",
    name: "Heo quay cháy tỏi",
    type: "pork",
    image: "G022",
    id: "G022",
  },
  {
    price: 74000,
    englishName: "Fried pork belly with lemongrass",
    name: "Ba rọi chiên sả",
    type: "pork",
    image: "G023",
    id: "G023",
  },
  {
    price: 82000,
    englishName: "Fried pork chop in black pepper lime sauce",
    name: "Sườn non ram muối tiêu chanh",
    type: "pork",
    image: "G024",
    id: "G024",
  },
  {
    price: 93000,
    englishName: "Fried pork chop in sour and sweet sauce",
    name: "Sườn xào chua ngọt",
    type: "pork",
    image: "G025",
    id: "G025",
  },
  {
    price: 74000,
    englishName: "Pork belly sauteed with garlic",
    name: "Ba rọi cháy tỏi",
    type: "pork",
    image: "G109",
    id: "G109",
  },
  {
    price: 87000,
    englishName: "Roasted pork sauteed with pickled cabbage",
    name: "Heo quay xào dưa cải",
    type: "pork",
    image: "G110",
    id: "G110",
  },
  {
    price: 74000,
    englishName: "Pork belly fried with fish sauce",
    name: "Ba rọi chiên nước mắm",
    type: "pork",
    image: "G111",
    id: "G111",
  },
  {
    price: 72000,
    englishName: "Deep fried catfish, dip in fish sauce and mango",
    name: "Cá trê chiên chấm nước mắm xoài",
    type: "fish",
    image: "G027",
    id: "G027",
  },
  {
    price: 75000,
    englishName: "Featherback fish cake sauteed in fish sauce",
    name: "Chả cá rim nước mắm",
    type: "fish",
    image: "G028",
    id: "G028",
  },
  {
    price: 75000,
    englishName: "Deep fried featherback fish cake",
    name: "Chả cá chiên giòn",
    type: "fish",
    image: "G029",
    id: "G029",
  },
  {
    price: 95000,
    englishName: "Red tilapia deep fried with tamarind sauce",
    name: "Cá diêu hồng quay me",
    type: "fish",
    image: "G031",
    id: "G031",
  },
  {
    price: 98000,
    englishName: "Red tilapia stewed with soybean paste",
    name: "Cá diêu hồng chưng tương",
    type: "fish",
    image: "G033",
    id: "G033",
  },
  {
    price: 95000,
    englishName: "Red tilapia steamed with onion",
    name: "Cá diêu hồng hấp hành",
    type: "fish",
    image: "G034",
    id: "G034",
  },
  {
    price: 65000,
    englishName: "Round scad braised with garlic and fish sauce",
    name: "Cá nục kho tỏi",
    type: "fish",
    image: "G120",
    id: "G120",
  },
  {
    price: 76000,
    englishName: "Catfish braised in clay pot",
    name: "Cá hú kho tộ",
    type: "fish",
    image: "G121",
    id: "G121",
  },
  {
    price: 92000,
    englishName: "Deep fried red tilapia, dip in fish sauce and mango",
    name: "Cá chiên giòn mắm xoài",
    type: "fish",
    image: "G122",
    id: "G122",
  },
  {
    price: 72000,
    englishName: "Capelin deep fried, dip in tamarind sauce",
    name: "Cá trứng chiên mắm me",
    type: "fish",
    image: "G123",
    id: "G123",
  },
  {
    price: 62000,
    englishName: "Tofu deep fried with lemongrass and shrimp paste",
    name: "Đậu hủ ruốc sả",
    type: "tofu",
    image: "G035",
    id: "G035",
  },
  {
    price: 90000,
    englishName: "Tofu sauteed with seafood",
    name: "Đậu hủ sốt hải sản",
    type: "tofu",
    image: "G036",
    id: "G036",
  },
  {
    price: 55000,
    englishName: "Tofu deep fried with spring onion and soy sauce",
    name: "Đậu hủ chiên hành",
    type: "tofu",
    image: "G037",
    id: "G037",
  },
  {
    price: 58000,
    englishName: "Tofu stir fried with chilli and lemongrass",
    name: "Đậu hủ chiên sả ớt",
    type: "tofu",
    image: "G038",
    id: "G038",
  },
  {
    price: 66000,
    englishName: "Tofu sauteed with salted egg yolk",
    name: "Đậu hủ sốt trứng muối",
    type: "tofu",
    image: "G115",
    id: "G115",
  },
  {
    price: 85000,
    englishName: "Boiled beef shank, dip in fish sauce and ginger",
    name: "Bắp bò luộc chấm mắm gừng",
    type: "beef",
    image: "G039",
    id: "G039",
  },
  {
    price: 86000,
    englishName: "Beef tendon sauteed with pickled cabbage",
    name: "Gân bò xào dưa cải",
    type: "beef",
    image: "G040",
    id: "G040",
  },
  {
    price: 86000,
    englishName: "Beef stir-fried with lemongrass and chilli",
    name: "Bò xào sả ớt",
    type: "beef",
    image: "G043",
    id: "G043",
  },
  {
    price: 90000,
    englishName: "Beef in dice sauteed with vegetables",
    name: "Bò lúc lắc",
    type: "beef",
    image: "G044",
    id: "G044",
  },
  {
    price: 90000,
    englishName: "Beef sauteed with green piper",
    name: "Bò sốt tiêu xanh",
    type: "beef",
    image: "G045",
    id: "G045",
  },
  {
    price: 94000,
    englishName: "Beef tendon sauteed with shiitake mushroom",
    name: "Gân bò hầm nấm đông cô",
    type: "beef",
    image: "G046",
    id: "G046",
  },
  {
    price: 90000,
    englishName: "Beef shank sauteed with okra",
    name: "Bắp bò xào lăn",
    type: "beef",
    image: "G112",
    id: "G112",
  },
  {
    price: 92000,
    englishName: "Beef shank sauteed with pickled cabbage",
    name: "Bắp bò xào dưa cải",
    type: "beef",
    image: "G113",
    id: "G113",
  },
  {
    price: 82000,
    englishName: "Clams sauteed with fish sauce",
    name: "Nghêu rim nước mắm",
    type: "seafood",
    image: "G047",
    id: "G047",
  },
  {
    price: 92000,
    englishName: "Shrimp sauteed with sea salt",
    name: "Tôm rang muối",
    type: "seafood",
    image: "G048",
    id: "G048",
  },
  {
    price: 92000,
    englishName: "Deep fried squid with salt (M)",
    name: "Mực chiên giòn xốc muối (nhỏ)",
    type: "seafood",
    image: "G049",
    id: "G049M",
  },
  {
    price: 120000,
    englishName: "Deep fried squid with salt (L)",
    name: "Mực chiên giòn xốc muối (lớn)",
    type: "seafood",
    image: "G049",
    id: "G049L",
  },
  {
    price: 82000,
    englishName: "Clams sauteed with tamarind sauce",
    name: "Nghêu rim me",
    type: "seafood",
    image: "G051",
    id: "G051",
  },
  {
    price: 92000,
    englishName: "Squid deep fried with fish sauce (M)",
    name: "Mực chiên nước mắm (nhỏ)",
    type: "seafood",
    image: "G053",
    id: "G053M",
  },
  {
    price: 123000,
    englishName: "Squid deep fried with fish sauce (L)",
    name: "Mực chiên nước mắm (lớn)",
    type: "seafood",
    image: "G053",
    id: "G053L",
  },
  {
    price: 92000,
    englishName: "Squid steamed with onion and ginger (M)",
    name: "Mực hấp hành gừng (nhỏ)",
    type: "seafood",
    image: "G055",
    id: "G055M",
  },
  {
    price: 126000,
    englishName: "Squid steamed with onion and ginger (L)",
    name: "Mực hấp hành gừng (lớn)",
    type: "seafood",
    image: "G055",
    id: "G055L",
  },
  {
    price: 70000,
    englishName: "Clam and tomato",
    name: "Canh nghêu",
    type: "soup",
    image: "G056",
    id: "G056",
  },
  {
    price: 75000,
    englishName: "Beef and pickled cabbage",
    name: "Canh dưa chua thịt bò",
    type: "soup",
    image: "G057",
    id: "G057",
  },
  {
    price: 55000,
    englishName: "Tofu",
    name: "Canh đậu hủ",
    type: "soup",
    image: "G058",
    id: "G058",
  },
  {
    price: 75000,
    englishName: "Bitter gourd and fish ball",
    name: "Canh khổ qua chả cá",
    type: "soup",
    image: "G059",
    id: "G059",
  },
  {
    price: 82000,
    englishName: "Sour and sweet with shrimp",
    name: "Canh chua tôm",
    type: "soup",
    image: "G060",
    id: "G060",
  },
  {
    price: 75000,
    englishName: "Vegetable and shrimp",
    name: "Canh rau xanh tôm",
    type: "soup",
    image: "G061",
    id: "G061",
  },
  {
    price: 70000,
    englishName: "Seaweed and tofu",
    name: "Canh rong biển đậu hủ",
    type: "soup",
    image: "G063",
    id: "G063",
  },
  {
    price: 75000,
    englishName: "Bottle gourd and shrimp",
    name: "Canh bầu nấu tôm",
    type: "soup",
    image: "G064",
    id: "G064",
  },
  {
    price: 70000,
    englishName: "Bitter gourd and tofu",
    name: "Canh khổ qua đậu hủ",
    type: "soup",
    image: "G065",
    id: "G065",
  },
  {
    price: 72000,
    englishName: "Chicken and sour creeper leaves",
    name: "Canh gà lá giang",
    type: "soup",
    image: "G066",
    id: "G066",
  },
  {
    price: 70000,
    englishName: "Tofu skin and mushroom",
    name: "Canh nấm tàu hủ ky",
    type: "soup",
    image: "G067",
    id: "G067",
  },
  {
    price: 75000,
    englishName: "Vegetable and fish ball",
    name: "Canh rau xanh chả cá",
    type: "soup",
    image: "G068",
    id: "G068",
  },
  {
    price: 75000,
    englishName: "Luffa gourd with shrimp and mushroom",
    name: "Canh mướp nấm tôm",
    type: "soup",
    image: "G069",
    id: "G069",
  },
  {
    price: 75000,
    englishName: "Field crab and jute leaves",
    name: "Canh cua rau đay",
    type: "soup",
    image: "G116",
    id: "G116",
  },
  {
    price: 70000,
    englishName: "Vegetable and minced pork",
    name: "Canh rau xanh thịt băm",
    type: "soup",
    image: "G117",
    id: "G117",
  },
  {
    price: 76000,
    englishName: "Sour and sweet with fish",
    name: "Canh chua cá",
    type: "soup",
    image: "G118",
    id: "G118",
  },
  {
    price: 70000,
    englishName: "Vegan sour and sweet",
    name: "Canh chua chay",
    type: "soup",
    image: "G119",
    id: "G119",
  },
  {
    price: 88000,
    englishName: "Salad with shrimp and squid",
    name: "Trộn tôm mực",
    type: "salad",
    image: "G071",
    id: "G071",
  },
  {
    price: 86000,
    englishName: "Salad with beef shank",
    name: "Nộm bắp bò",
    type: "salad",
    image: "G072",
    id: "G072",
  },
  {
    price: 86000,
    englishName: "Salad with bottle gourd, shrimp and pork",
    name: "Gỏi bầu tôm thịt",
    type: "salad",
    image: "G073",
    id: "G073",
  },
  {
    price: 70000,
    englishName: "Salad with mushroom",
    name: "Gỏi nấm",
    type: "salad",
    image: "G074",
    id: "G074",
  },
  {
    price: 72000,
    englishName: "Ghem springrolls",
    name: "Chả giò Ghém",
    type: "salad",
    image: "G075",
    id: "G075",
  },
  {
    price: 52000,
    englishName: "Vegetable stir fried with garlic",
    name: "Rau xào tỏi",
    type: "vegetables",
    image: "G076",
    id: "G076",
  },
  {
    price: 72000,
    englishName: "Vegetable stir fried with beef",
    name: "Rau xào bò",
    type: "vegetables",
    image: "G077",
    id: "G077",
  },
  {
    price: 62000,
    englishName: "Vegetable stir fried with fermented tofu",
    name: "Rau xào chao",
    type: "vegetables",
    image: "G078",
    id: "G078",
  },
  {
    price: 60000,
    englishName: "Cooked vegetables, dip in fermented tofu",
    name: "Rau củ luộc chấm chao",
    type: "vegetables",
    image: "G079",
    id: "G079",
  },
  {
    price: 60000,
    englishName: "Bean sprout stir fried with minced pork and satay sauce",
    name: "Giá xào sa tế thịt băm",
    type: "vegetables",
    image: "G080",
    id: "G080",
  },
  {
    price: 60000,
    englishName: "Baby corn stir fried with vegetables",
    name: "Bắp non xào rau củ",
    type: "vegetables",
    image: "G081",
    id: "G081",
  },
  {
    price: 66000,
    englishName: "Bitter gourd stir fried with egg",
    name: "Khổ qua xào trứng",
    type: "vegetables",
    image: "G124",
    id: "G124",
  },
  {
    price: 60000,
    englishName: "Luffa gourd stir fried with mushroom",
    name: "Mướp xào nấm",
    type: "vegetables",
    image: "G125",
    id: "G125",
  },
  {
    price: 62000,
    englishName: "Vegetable stir fried with oyster sauce",
    name: "Rau củ sốt dầu hào",
    type: "vegetables",
    image: "G126",
    id: "G126",
  },
  {
    price: 95000,
    englishName: "Caramelized dip and cooked vegetables",
    name: "Kho quẹt - Rau củ luộc",
    type: "vegetables",
    image: "G127",
    id: "G127",
  },
  {
    price: 10000,
    englishName: "Steam rice in clay pot",
    name: "Cơm thố [1 người]",
    type: "side_dish",
    image: "G082",
    id: "G082",
  },
  {
    price: 20000,
    englishName: "Steam rice in bowl",
    name: "Cơm tô [2-3 người]",
    type: "side_dish",
    image: "G083",
    id: "G083",
  },
  {
    price: 10000,
    englishName: "Pickled cabbage",
    name: "Dưa cải",
    type: "side_dish",
    image: "G084",
    id: "G084",
  },
  {
    price: 10000,
    englishName: "Pickled garden-egg",
    name: "Cà pháo",
    type: "side_dish",
    image: "G086",
    id: "G086",
  },
  {
    price: 220000,
    englishName: "Chicken and sour creeper leaves (M)",
    name: "Lẩu gà lá giang (nhỏ)",
    type: "hotpot",
    image: "G105",
    id: "G105M",
  },
  {
    price: 320000,
    englishName: "Chicken and sour creeper leaves (L)",
    name: "Lẩu gà lá giang (lớn)",
    type: "hotpot",
    image: "G105",
    id: "G105L",
  },
  {
    price: 240000,
    englishName: "Duck and fermented tofu (M)",
    name: "Lẩu vịt nấu chao (nhỏ)",
    type: "hotpot",
    image: "G106",
    id: "G106M",
  },
  {
    price: 340000,
    englishName: "Duck and fermented tofu (L)",
    name: "Lẩu vịt nấu chao (lớn)",
    type: "hotpot",
    image: "G106",
    id: "G106L",
  },
  {
    price: 220000,
    englishName: "Beef and satay (M)",
    name: "Lẩu bò sa tế (nhỏ)",
    type: "hotpot",
    image: "G107",
    id: "G107M",
  },
  {
    price: 320000,
    englishName: "Beef and satay (L)",
    name: "Lẩu bò sa tế (lớn)",
    type: "hotpot",
    image: "G107",
    id: "G107L",
  },
  {
    price: 220000,
    englishName: "Chicken and lemongrass (M)",
    name: "Lẩu gà hầm sả (nhỏ)",
    type: "hotpot",
    image: "G108",
    id: "G108M",
  },
  {
    price: 320000,
    englishName: "Chicken and lemongrass (L)",
    name: "Lẩu gà hầm sả (lớn)",
    type: "hotpot",
    image: "G108",
    id: "G108L",
  },
  {
    price: 210000,
    englishName: "Field crab, pork, beef, squid and tofu (M)",
    name: "Lẩu cua đồng (nhỏ)",
    type: "hotpot",
    image: "G128",
    id: "G128M",
  },
  {
    price: 300000,
    englishName: "Field crab, pork, beef, squid and tofu (L)",
    name: "Lẩu cua đồng (lớn)",
    type: "hotpot",
    image: "G128",
    id: "G128L",
  },
  {
    price: 220000,
    englishName: "Featherback fish cake and vegetable (M)",
    name: "Lẩu cá thát lát (nhỏ)",
    type: "hotpot",
    image: "G129",
    id: "G129M",
  },
  {
    price: 340000,
    englishName: "Featherback fish cake and vegetable (L)",
    name: "Lẩu cá thát lát (lớn)",
    type: "hotpot",
    image: "G129",
    id: "G129L",
  },
  {
    price: 220000,
    englishName: "Chicken and green chilli (M)",
    name: "Lẩu gà ớt hiểm (nhỏ)",
    type: "hotpot",
    image: "G130",
    id: "G130M",
  },
  {
    price: 320000,
    englishName: "Chicken and green chilli (L)",
    name: "Lẩu gà ớt hiểm (lớn)",
    type: "hotpot",
    image: "G130",
    id: "G130L",
  },
  {
    price: 0,
    englishName: "Prawn in pineapple sauce",
    name: "Tôm sốt thơm",
    type: "party",
    image: "G133",
    id: "G133",
  },
  {
    price: 0,
    englishName: "Seabass in passion fruit sauce",
    name: "Cá chẽm sốt chanh dây",
    type: "party",
    image: "G134",
    id: "G134",
  },
  {
    price: 0,
    englishName: "Prawn in tamarind sauce",
    name: "Tôm sốt me",
    type: "party",
    image: "G135",
    id: "G135",
  },
  {
    price: 0,
    englishName: '"Cu hu dua" salad with pickled pig ears ',
    name: "Gỏi củ hủ dừa tai heo",
    type: "party",
    image: "G136",
    id: "G136",
  },
  {
    price: 0,
    englishName: "Salad with seafood",
    name: "Gỏi hải sản",
    type: "party",
    image: "G137",
    id: "G137",
  },
  {
    price: 0,
    englishName: "Pork leg steamed with four kinds of vegetables",
    name: "Giò heo tứ quý",
    type: "party",
    image: "G138",
    id: "G138",
  },
  {
    price: 0,
    englishName: "Pork leg steamed with shiitake mushroom",
    name: "Giò heo hầm nấm dông cô",
    type: "party",
    image: "G139",
    id: "G139",
  },
  {
    price: 0,
    englishName: "Salad with chicken and cabbage",
    name: "Gỏi gà xé phay",
    type: "party",
    image: "G140",
    id: "G140",
  },
  {
    price: 0,
    englishName: "Chicken grilled with salt and chilli",
    name: "Gà nướng muối",
    type: "party",
    image: "G141",
    id: "G141",
  },
  {
    price: 0,
    englishName: "Chicken tray [roasted, salad, with bread and sticky rice]",
    name: " Gà lên mâm ",
    type: "party",
    image: "G142",
    id: "G142",
  },
  {
    price: 0,
    englishName: "Chicken steamed with sweet fermented rice",
    name: "Gà hấp cơm rượu",
    type: "party",
    image: "G143",
    id: "G143",
  },
  {
    price: 0,
    englishName: "Curry with duck",
    name: "Cà ri vịt",
    type: "party",
    image: "G144",
    id: "G144",
  },
  {
    price: 0,
    englishName: "Curry with shrimp",
    name: "Cà ri tôm",
    type: "party",
    image: "G145",
    id: "G145",
  },
  {
    price: 0,
    englishName: "Curry with chicken",
    name: "Cà ri gà",
    type: "party",
    image: "G146",
    id: "G146",
  },
  {
    price: 0,
    englishName: "Curry with crab meat",
    name: "Cà ri cua",
    type: "party",
    image: "G147",
    id: "G147",
  },
  {
    price: 0,
    englishName: "Snakehead fish steamed with coconut milk",
    name: "Cá lóc bó xổ hấp cốt dừa",
    type: "party",
    image: "G148",
    id: "G148",
  },
  {
    price: 0,
    englishName: "Seabass steamed with spring onion",
    name: "Cá lóc hấp hành",
    type: "party",
    image: "G149",
    id: "G149",
  },
];

export interface DishTypeInfo {
  name: string;
  value: string;
}

const DISH_TYPES: Array<DishTypeInfo> = [
  {
    name: "Gà",
    value: "chicken",
  },
  {
    name: "Vịt",
    value: "duck",
  },
  {
    name: "Trứng",
    value: "egg",
  },
  {
    name: "Heo",
    value: "pork",
  },
  {
    name: "Bò",
    value: "beef",
  },
  {
    name: "Hải sản",
    value: "seafood",
  },
  {
    name: "Đậu hủ",
    value: "tofu",
  },
  {
    name: "Cá",
    value: "fish",
  },
  {
    name: "Salad",
    value: "salad",
  },
  {
    name: "Rau cải",
    value: "vegetables",
  },
  {
    name: "Canh",
    value: "soup",
  },
  {
    name: "Món phụ",
    value: "side_dish",
  },
  {
    name: "Tráng miệng",
    value: "dessert",
  },
  {
    name: "Lẩu",
    value: "hotpot",
  },
  {
    name: "Món tiệc",
    value: "party",
  },
];

const INGREDIENT_MAP: Record<string, Array<DishInfo>> = {};

const DISH_MAP: Record<string, DishInfo> = {};

// INGREDIENTS.forEach((item) => (INGREDIENT_MAP[item.value] = []));

DISHES.forEach((dish) => {
  const a = INGREDIENT_MAP[dish.type];
  DISH_MAP[dish.id] = dish;
  if (a) {
    a.push(dish);
  }
});

export interface ComboInformation {
  name: string;
  value: string;
  description: string;
}

const COMBOS: Array<ComboInformation> = [
  {
    name: "Combo Tiện Lợi",
    value: "convenient",
    description: "Hai bữa trưa và tối chỉ 196,000 VND.",
  },
  {
    name: "Combo Gia Đình",
    value: "family",
    description: "Hai bữa trưa và tối cho cả nhà 2-4 người chỉ 380,000 VND.",
  },
  {
    name: "Combo Tiệc",
    value: "party",
    description: "Combo tiệc tại nhà với các món chính, món lẩu, món gỏi",
  },
  {
    name: "Combo Cuối Tuần",
    value: "weekend",
    description: "Lẩu và 2 món ăn cho cả nhà 2-4 người chỉ 360,000 VND",
  },
];

export { DISH_TYPES, DISHES, INGREDIENT_MAP, COMBOS, DISH_MAP };
